### ISSUE TITLE
Пустой ответ

### ISSUE THREAD

**Issue by xdirex** [GetResponse/getresponse-api-php#6]
$getresponse = new GetResponse('....');
$getresponse->enterprise_domain = '....';
$getresponse->api_url = 'http://api.getresponse360.com/';
$result = $getresponse->accounts();

print_r($result);

В результате сервер не чего не отдает.

**Comment by mzubrzycki** [comment]
Hi xdirex.

You provided wrong api url. It should be:
`$gr->api_url = 'https://api3.getresponse360.com/v3';`
